### ISSUE TITLE
'Color' is not defined

### ISSUE THREAD

**Issue by mfraser** [ThePiHut/rgbxmastree#1]
Trying the examples huecycle.py, rgb.py and onebyone.py, I get the error
NameError: name 'Color' is not defined

**Comment by maurycyg** [comment]
you need to import it:
```from colorzero import Color```

**Comment by ajgbarnes** [comment]
I created a pull request to fix this and also it should be setting the tree.color attribute not the tree variable itself.

**Comment by maurycyg** [comment]
I'll add on top of that tomorrow with a graceful exit on keyboard
interruption

**Comment by bennuttall** [comment]
Sorry, fixed the examples now.
