### ISSUE TITLE
Large CPU draw

### ISSUE THREAD

**Issue by Mohoganogan** [ThePiHut/rgbxmastree#11]
The example code are very CPU intensive.  On a pi zero the cpu is running at 95%+

**Comment by bennuttall** [comment]
which example?

**Comment by Mohoganogan** [comment]
Only the random sparkles does not use 95%+ of the cpu on a zero. Installed on a clean minimal raspian install.

**Comment by bennuttall** [comment]
I guess that's the only one with a sleep in it. The rest just go as fast as they can. If you need to free up resources to do something else, you could try adding in a sleep to slow it down. If you don't, it should be fine at 95%.
