### ISSUE TITLE
questions about the SPI pins

### ISSUE THREAD

**Issue by tinker2much** [ThePiHut/rgbxmastree#13]
This is more a request for information than an issue. I just wonder why you're not using the actual SPI pins, 19 and 23. I've heard of "hardware SPI" versus "bit banging", and it seems you're doing the latter? - 
physical pin 22 == GPIO 25 (used for clock? )
physical pin 32 == GPIO 12 (used for data? )

Could you please provide the thinking behind your approach?

**Comment by bennuttall** [comment]
The pixels don't require precise timing or anything, so software SPI is fine. And if you are doing a Christmas project using two GPIO pins, why not use pins 12 and 25 to mark the date? A kind of Christmas Easter Egg.

**Comment by tinker2much** [comment]
I missed the Easter egg (hangs head).

I may have some further questions. Would you be willing to hear them, and if so would you prefer to do this in direct emails like this one, in the issue on GitHub, or on the raspberry forum where I’ve had a thread going for a while? 


> On Jan 7, 2020, at 11:22 AM, Ben Nuttall <notifications@github.com> wrote:
> 

﻿
The pixels don't require precise timing or anything, so software SPI is fine. And if you are doing a Christmas project using two GPIO pins, why not use pins 12 and 25 to mark the date? A kind of Christmas Easter Egg.
