### ISSUE TITLE
Lights do not come on when running 'python3 tree.py'

### ISSUE THREAD

**Issue by explodinghat** [ThePiHut/rgbxmastree#17]
Hi, having some issues following this guide. I have installed the RGB tree onto a Pi Zero W with a fresh install of raspbian lite OS.
The lights do not come on when testing by running python3 tree.py and I'm not too sure what to troubleshoot next. 
Is there a way I can check my GPIO connection?

**Comment by bennuttall** [comment]
Do you have any other add-on boards you could try?

**Comment by explodinghat** [comment]
Yeah, I've tried another board and it is working. Also tried the RGB tree on 3 Pi's (2 Zero W's, one Pi 400) and no joy - I guess it's looking like the tree may be busted? :(

**Comment by Leesneaks** [comment]
I've had two of these boards so far and neither are working.
Its been tried on 4 different devices.
I have a replacement for one of them coming soon but I'm expecting the same.
I'm either having very bad luck with the boards I've received or something isn't correct when it comes to its usage with the new boards being shipped.

**Comment by explodinghat** [comment]
Hmm. That seems ominous! Well I’ve got the part RMA’d anyway so currently awaiting a replacement

**Comment by i-hardy** [comment]
I was having the same issue, but when I tried it on a Pimoroni Black HAT Hack3r the tree worked just fine. No idea why, but it just doesn't seem to like the normal GPIO pins.

**Comment by Meneer-T** [comment]
I have the exact same issue and did some testing.
The interesting thing is that when I connect 5V-in, Ground and the 2 data wires with Dupont cable, the tree works perfectly!

**Comment by krisztianzagonyi-mintestio** [comment]
I have the exact same issue, but mine doesn't work with cables neither.
Any update on this?
My other hats are working fine.
@bennuttall

**Comment by WalterRietveld** [comment]
I have the same issue only led nr 6 seems to respond (always in red).
Any solution known yet?

**Comment by barthawk** [comment]
I have the same issue on several devices, I don't have a cable to test it with right now.  The only other thing I would note is that tree.py does nothing, but if I run some of the other examples - like randomsparkles or onebyone.  A single LED will light up (one closest to the Ethernet port on a Pi4).

**Comment by Meneer-T** [comment]
I got a replacement tree which worked fine, so please keep in mind that hardware failures are possible.

**Comment by explodinghat** [comment]
Yeah I got a replacement and this is working fine - it was a hardware issue.
