### ISSUE TITLE
Problem with individual led control

### ISSUE THREAD

**Issue by lindscornell** [ThePiHut/rgbxmastree#19]
Hi. I have installed the RGBXmasTree on a Pi Zero W. It works except for the individual pixel control... e.g. tree[1].color = (1,0,1) does nothing; the example code with loops for pixels do nothing...  I modified tree.py so that the class def for RGBXmasTree __init__ sets each led separately - i.e. self._value = [(0,1,1),(1,1,0),(0,1,0), ... ] rather than a value * pixels and it duly sets each led to the individual colour, but as I say, I cannot get the leds to change individually after that...  Any ideas?

**Comment by SVendittelli** [comment]
I delt with similar problems in my fork, maybe you will find it useful. I got around it by copying the current value of the tree and only changing the pixels in the copy that I wanted https://github.com/SVendittelli/rgbxmastree/blob/master/patterns/tree.py

**Comment by dmaznytskyi** [comment]
Which python version are you using? 
For Python 2.7.16 individual controls don't work at all.
For Python 3.7.3 individual controls working perfectly.

Try to run scripts `python3 randomsparkles.py`, not `python randomsparkles.py`.

**Comment by lindscornell** [comment]
Thanks for the comment: I had Python 2.7.13 and 3.5.3 which were reported as the latest available under Raspbian on the Pi Zero. Since there seemed to be no way to update to 3.7.3, I reinstalled the OS with the latest and now have 3.7.3 and a working tree.
