### ISSUE TITLE
Labeled Pins Use? 

### ISSUE THREAD

**Issue by rcarteraz** [ThePiHut/rgbxmastree#29]
There are 4 pins labelled D, C, P, and G in the middle of the tree but nothing detailing what they are used for. At first I thought I might be missing an LED but then I realized the example pictures on the website has the same thing.

**Comment by bennuttall** [comment]
Data, Clock, Power, Ground - you can connect more LEDs on a strip and control them all together.

**Comment by rcarteraz** [comment]
> Data, Clock, Power, Ground - you can connect more LEDs on a strip and control them all together.

Thank you!
