### ISSUE TITLE
No license attached to repo!

### ISSUE THREAD

**Issue by BumblebeeMan** [ThePiHut/rgbxmastree#32]
Hi ThePiHut-Crew,

every christmas I set-up my [RGB Xmas tree](https://thepihut.com/products/3d-rgb-xmas-tree-for-raspberry-pi) to be a Cheerlight (see [cheerlights.com](cheerlights.com)). My implementation is currently based on your "tree.py".

Unfortunately, there isn't any licensing information is attached to your repo. Are you able to add a license?
Or do I have to write my own "tree.py" (to get my project released on github)?

Kind regards,
- BumblebeeMan *buzz, buzz*

**Comment by bennuttall** [comment]
It is an extension of gpiozero, so it has the same licence as that: https://github.com/gpiozero/gpiozero/blob/master/LICENSE.rst

**Comment by BumblebeeMan** [comment]
Thanks for your clarification that it is under BSD-3-Clause!
