### ISSUE TITLE
Can't run tree.py 

### ISSUE THREAD

**Issue by courseiam** [ThePiHut/rgbxmastree#35]
I get the following when I try to run tree.py:

> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 22, in <module>
>     from importlib_metadata import entry_points
>   File "/usr/lib/python3/dist-packages/importlib_metadata/__init__.py", line 6, in <module>
>     import zipp
>   File "/usr/lib/python3/dist-packages/zipp.py", line 12, in <module>
>     import more_itertools
>   File "/usr/lib/python3/dist-packages/more_itertools/__init__.py", line 1, in <module>
>     from .more import *  # noqa
>     ^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3/dist-packages/more_itertools/more.py", line 24, in <module>
>     from random import random, randrange, uniform
>   File "/home/Dan/random.py", line 1, in <module>
>     from tree import RGBXmasTree
>   File "/home/Dan/tree.py", line 1, in <module>
>     from gpiozero import SPIDevice, SourceMixin
> ImportError: cannot import name 'SPIDevice' from partially initialized module 'gpiozero' (most likely due to a circular import) (/usr/lib/python3/dist-packages/gpiozero/__init__.py)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/Dan/tree.py", line 1, in <module>
>     from gpiozero import SPIDevice, SourceMixin
>   File "/usr/lib/python3/dist-packages/gpiozero/__init__.py", line 19, in <module>
>     from .pins import (
>   File "/usr/lib/python3/dist-packages/gpiozero/pins/__init__.py", line 21, in <module>
>     from ..devices import Device
>   File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 24, in <module>
>     from importlib.metadata import entry_points
>   File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 17, in <module>
>     from . import _adapters, _meta
>   File "/usr/lib/python3.11/importlib/metadata/_adapters.py", line 3, in <module>
>     import email.message
>   File "/usr/lib/python3.11/email/message.py", line 15, in <module>
>     from email import utils
>   File "/usr/lib/python3.11/email/utils.py", line 28, in <module>
>     import random
>   File "/home/Dan/random.py", line 1, in <module>
>     from tree import RGBXmasTree
>   File "/home/Dan/tree.py", line 1, in <module>
>     from gpiozero import SPIDevice, SourceMixin
> ImportError: cannot import name 'SPIDevice' from partially initialized module 'gpiozero' (most likely due to a circular import) (/usr/lib/python3/dist-packages/gpiozero/__init__.py)

Didn't have this issue last year. I've tried on a fresh install of RP OS too with same issue.

**Comment by Trotter73** [comment]
Hey, 

What image did you flash your Pi with?

I used the Legacy Lite edition and it's working perfectly.....

**Comment by courseiam** [comment]
The latest version, believe it's called Bookworm. I'll try with an older version and get back to you.

**Comment by Trotter73** [comment]
Things changed a lot with Bookworm and Python, broke loads of things, I would like to bet with the legacy image you will be grand...

**Comment by courseiam** [comment]
Yep now work fine. Thanks for pointing me in the right direction.

**Comment by courseiam** [comment]
Ok, now I get the following when trying to run randomsparkles.py:

> Traceback (most recent call last):
>   File "/home/Dan/randomsparkles.py", line 1, in <module>
>     from tree import RGBXmasTree
>   File "/home/Dan/tree.py", line 3, in <module>
>     from statistics import mean
>   File "/usr/lib/python3.9/statistics.py", line 105, in <module>
>     import random
>   File "/home/Dan/random.py", line 1, in <module>
>     from tree import RGBXmasTree
> ImportError: cannot import name 'RGBXmasTree' from partially initialized module 'tree' (most likely due to a circular import) (/home/Dan/tree.py)

**Comment by Trotter73** [comment]
I'll try another fresh install for you here and see if I get the same... I'll get onto that in a bit....

**Comment by courseiam** [comment]
Thanks. It seems to run tree.py once and maybe some of the examples once or twice then that's it, even after a reboot. Just tested a none related python project (written on my laptop) and they seem to work fine. I'm so confused by this.

**Comment by Trotter73** [comment]
So...

To run the examples you need to copy tree.py into the examples directory....

So from a fresh install of legacy light.....

sudo apt update
sudo apt upgrade

sudo apt install python3-gpiozero python3-pigpio pigpio git

git clone https://github.com/ThePiHut/rgbxmastree

cd rgbxmastree

cp tree.py examples/

Doing that, all examples ran OK here on a PiZero2

**Comment by courseiam** [comment]
Still the same issue. Ran tree.py fine, then when trying one of the examples it  doesn't work and tree will not run again. See error below. Are you running 32 or 64 bit?

> Traceback (most recent call last):
>   File "/home/Dan/rgbxmastree/randomsparkles.py", line 1, in <module>
>     from tree import RGBXmasTree
>   File "/home/Dan/rgbxmastree/tree.py", line 3, in <module>
>     from statistics import mean
>   File "/usr/lib/python3.9/statistics.py", line 105, in <module>
>     import random
>   File "/home/Dan/rgbxmastree/random.py", line 1, in <module>
>     from tree import RGBXmasTree
> ImportError: cannot import name 'RGBXmasTree' from partially initialized module 
> 'tree' (most likely due to a circular import) (/home/Dan/rgbxmastree/tree.py)

**Comment by courseiam** [comment]
I don't know what I've done, but it's working. Run the examples multiple times with no issues and now running my custom script. Thanks for your help @Trotter73

**Comment by Trotter73** [comment]
I used this image...

https://downloads.raspberrypi.com/raspios_oldstable_lite_armhf/images/raspios_oldstable_lite_armhf-2024-10-28/2024-10-22-raspios-bullseye-armhf-lite.img.xz

I'm wondering if it's because you ran tree.py first maybe? Other than that I'm out of ideas, like I said with the steps I posted above it works fine here.... Sorry.

**Comment by Trotter73** [comment]
> I don't know what I've done, but it's working. Run the examples multiple times with no issues and now running my custom script. Thanks for your help @Trotter73

Glad ur up and running! Are your scripts up on github ?

**Comment by courseiam** [comment]
I've figured out what was causing the issue, and it's all my fault. I named my script random.py and I think it was clashing with the built in random. They are not. All I've done is edit randomsparkles.py to have an on and off time on the light. I can add it if you'd like.

**Comment by Trotter73** [comment]
Ahhh right, cool, glad you sorted it !!

You might want to have a look at this repo, not mine, but I've used it for my tree for the last few years... 

https://github.com/rgooding/rgbxmastree.git

I create a debian service for the script and then use crontab to turn the lights on and off again.......

**Comment by courseiam** [comment]
Thanks, I'll take a look. Guess I can close this now.
