### ISSUE TITLE
Colorzero library missing

### ISSUE THREAD

**Issue by goddarpm** [ThePiHut/rgbxmastree#8]
Where can I find the correct colorzero library for use with this project? I’ve searched github and found a library but it doesn’t work with this project. 
Any help would be appreciated.

**Comment by SVendittelli** [comment]
`colorzero` is part of the `gpiozero` library which comes pre-installed on raspbian (see [here](https://gpiozero.readthedocs.io/en/stable/)). The examples given should be run with `python3` if you are not already. If that doesn't help then try installing `gpiozero` from [here](https://gpiozero.readthedocs.io/en/stable/installing.html).

**Comment by SVendittelli** [comment]
First please ensure you are using `python3` to run any example files, you'll get a lot of missing dependencies if you don't. I believe `colorzero` should come pre-installed on raspbian but if you are running a different OS or have highly customised it then try the steps [here](https://colorzero.readthedocs.io/en/release-1.1/install.html).

Note my previous comment was inaccurate and unhelpful so I have deleted it and replaced it with this one.

**Comment by bennuttall** [comment]
Everything you need is pre-installed in Raspbian desktop. For server you just need `sudo apt install python3-gpiozero` which brings in colorzero too. I'll add that to the readme.

**Comment by goddarpm** [comment]
Thanks for the replies. Reloaded the OS and now working
